import { Navbar } from '@/components';
import { UserProvider } from '@auth0/nextjs-auth0/client';
import '@/styles/index.css'

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <UserProvider>
        <body>
          <Navbar/>
          {children}
        </body>
      </UserProvider>
    </html>
  );
}
